Add -C option to specify the working folder.
dalibo/ldap2pg pull request #602
Opened 2024-04-02 13:22 UTC by pirlgon

2024-04-03 06:50 UTC, bersace requested changes

2024-04-03 06:50 UTC, bersace commented on cmd/ldap2pg/flags.go
> +	_ = viper.BindEnv("directory", "LDAP2PG_DIRECTORY")
Hmm, pas sûr de vouloir ça. Je propose de le laisser pour plus tard.

2024-04-03 07:41 UTC, pirlgon commented on cmd/ldap2pg/flags.go
> +	_ = viper.BindEnv("directory", "LDAP2PG_DIRECTORY")
de quoi parles tu exactement? de l'association avec une var d'env?

2024-04-03 07:55 UTC, bersace commented on cmd/ldap2pg/flags.go
> +	_ = viper.BindEnv("directory", "LDAP2PG_DIRECTORY")
exactement ! :-)

2024-04-05 07:05 UTC, bersace approved these changes

2024-04-05 09:10 UTC, merged